on:
  push:
    branches: 
      - main

env:
  COVEO_PLATFORM_ENV: 'stg'
jobs:
  qa-deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Deploy to Staging
        uses: ./.github/actions/deploy
        with:
          environment: $COVEO_PLATFORM_ENV
          api-key: ${{ secrets.COVEO_API_KEY }}
  prod-deploy:
    needs: qa-deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to Production
        uses: ./.github/actions/deploy
        with:
          environment: $COVEO_PLATFORM_ENV
          api-key: ${{ secrets.COVEO_API_KEY }}