name: Refresh Branch
on:
  workflow_dispatch:
jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      COVEO_PLATFORM_ENV: 'stg'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get first commit
        id: first-commit
        run: echo "::set-output name=first_commit::$(git log origin/main..$GITHUB_REF_NAME --oneline | tail -1)"
      - uses: actions-ecosystem/action-regex-match@v2
        name: Get Org ID
        id: org-id
        with:
          text: ${{ steps.first-commit.outputs.first_commit }}
          regex: '^\w{7} setup (\w*) branch \[skip CI\]$'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Login to Coveo
        uses: ./.github/actions/login
        with:
          username: ${{ env.COVEO_MACHINE_USERNAME }}
          password: ${{ env.COVEO_MACHINE_PASSWORD }}
          environment: ${{ env.COVEO_PLATFORM_ENV }}
      - name: Pull Org Content
        run: npx @coveo/cli org:resources:pull -o ${{ steps.org-id.outputs.group1 }} -f
      - name: Commit & Push update
        run: |
          git config --global user.email action@github.com
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "update "$ORG_ID" branch [skip CI]" 
          git push
