name: Setup Dev Env
on:
  issues:
    types:
      - opened
jobs:
  create-env-discussion:
    runs-on: ubuntu-latest
    env:
      COVEO_MACHINE_USERNAME: ${{ secrets.COVEO_MACHINE_USERNAME }}
      COVEO_MACHINE_PASSWORD: ${{ secrets.COVEO_MACHINE_PASSWORD }}
      COVEO_PLATFORM_ENV: 'stg'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Verify author
        run: npm run check-user
      - name: Extract org name & email from issue description
        id: issue-data
        run: npm run extract-data
      - name: Login to Coveo
        uses: ./.github/actions/login
        with:
          username: ${{ env.COVEO_MACHINE_USERNAME }}
          password: ${{ env.COVEO_MACHINE_PASSWORD }}
          environment: ${{ env.COVEO_PLATFORM_ENV }}
      - name: Create Organization
        run: npx @coveo/cli org:create $NAME -s
        env:
          NAME: ${{steps.issue-data.outputs.orgname}}
      - name: Deploy resources on Organization
        run: npx @coveo/cli org:resources:push -s
      - name: Add User to Organization & Get Org ID
        run: npm run add-user
        env:
          NAME: ${{steps.issue-data.outputs.orgname}}
          EMAIL: ${{steps.issue-data.outputs.email}}
      - name: Create dev branch
        env:
          NAME: ${{steps.issue-data.outputs.orgname}}
        run: |
          git config --global user.email action@github.com
          git config --global user.name "GitHub Action"
          git checkout -b "dev/$NAME"
          git commit -m "setup "$ORG_ID" branch [skip CI]" --allow-empty
          git push --set-upstream origin "dev/$NAME"
      - name: Answer issue
        run: npm run answer-issue
        env:
          NAME: ${{steps.issue-data.outputs.orgname}}
          GHAPP_APP_ID: ${{ secrets.GHAPP_APP_ID }}
          GHAPP_PRIVATE_KEY: ${{ secrets.GHAPP_PRIVATE_KEY }}
          GHAPP_CLIENT_ID: ${{ secrets.GHAPP_CLIENT_ID }}
          GHAPP_CLIENT_SECRET: ${{ secrets.GHAPP_CLIENT_SECRET }}
          GHAPP_INSTALLATION_ID: ${{ secrets.GHAPP_INSTALLATION_ID }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifacts
          path: ./scripts/artifacts
